annotator:
    method : ''

dataset:
    max_samples: 20
    label_schema:  ["1","2","3","4","5"]

predictor:
    method : 'llm'
    config:
        prompt: 'prompts/predictor_completion/prediction_generation.prompt'
        mini_batch_size: 1
        llm:
            type: 'Azure'
            name: 'gpt-35-turbo-1106' #'gpt-3.5-turbo-1106'
        num_workers: 2

meta_prompts:
    folder: 'prompts/meta_prompts_generation'
    warmup: 1

eval:
    function_name: 'ranking'
    error_threshold: 4

