openai:
  OPENAI_API_KEY: ''
  OPENAI_API_BASE: ''
  OPENAI_ORGANIZATION: ''

azure:
  AZURE_OPENAI_API_KEY: '2de3b03c4ebd4f1f8681ce7d86ef475d'
  AZURE_OPENAI_ENDPOINT: 'https://tachikoma.openai.azure.com/'
  OPENAI_API_VERSION: '2024-02-01'

google:
  GOOGLE_API_KEY: ''